<?php
declare(strict_types=1);

namespace App\Modules\Homepage\Controllers;

use App\Modules\Common\Controllers\ControllerBase as CommonController;

class ControllerBase extends CommonController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}